name: RJTracker

options:
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.2.0"
    CURRENT_PROJECT_VERSION: "3"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual
    SWIFT_EMIT_LOC_STRINGS: YES

targets:
  RJTracker:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - Info.plist
          - RJTracker.entitlements
          - Resources
    resources:
      - path: App/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: eu.rjuhas.rjtracker
        PRODUCT_NAME: RJ Tracker
        INFOPLIST_FILE: App/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_ENTITLEMENTS: App/RJTracker.entitlements
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

schemes:
  RJTracker:
    build:
      targets:
        RJTracker: all
    run:
      config: Debug
    archive:
      config: Release
